#databases:
#  - name: mysite
#    databaseName: mysite
#    user: mysite

services:
  - type: web
    name: houedu
    env: python
    region: singapore
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
#      - key: DATABASE_URL
#        fromDatabase:
#          name: houedu_v2
#          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4